name = "formalmethods-project"

[package]
name = "formalmethods-project"
version = "0.1.0"

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "coinductive"
git = "https://github.com/ISTA-PLV/coinductive"
rev = "main"

[[require]]
name = "cslib"
git = "https://github.com/leanprover/cslib"
rev = "main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.30.0-rc2"

[[lean_lib]]
name = "FormalmethodsProject"
roots = ["src"]